- Id: repo.resources
  Evaluator: string-compare
  Version: 1
  Forms:
    - Fields:
      - Id: guid
        Fields:
          - Id: lookup
            Parameters:
              endpoint: '{url:base}/s/resource/csv/translate?id={0}&format=json&alf_ticket={auth:ticket}'
              resource-key: guid
              resource-value: label
              resource-error: error
          - Id: query
            Parameters:
              endpoint: '{url:base}/s/resource/csv/search?property={parameter:qname}&query={0}&format=json&alf_ticket={auth:ticket}'
              resource-key: guid
              resource-value: label
              resource-error: error
