- Id: some-id # Id of the form. This id is used by the evaluator to determine if this configuration applies
  Evaluator: string-compare|node-type|aspect # Type of evaluator to use to determine if this configuration applies
  Version: 1 # Version of the configuration schema. Always 1 for now.
  Forms:
    - Id: null # Id of the form. Defaults to null when omitted.
      Fields: # Fieldsets contained in this form
        - Id: template # Id of the fieldset. Defaults to the empty string when omitted.
          Text: Template fieldset # Title of the fieldset
          Description: This is a description of what is in the fieldset
          Help: This is extended help text about the fieldset
          Template: null # Template to use for the fieldset
          Parameters: {} # Additional parameters for the fieldset template
          Fields: # Fields contained in this fieldset
            - Id: cm:name # Id of the field
              Text: Name # Label of the field
              Help: The filename of the document # Helptext about the fieldset
              Template: null # Template to use for the field
              Parameters: {} # Additional parameters for the field template
              ReadOnly: false # Forces the field to always be rendered as rendermode View
              RenderMode: # Determines in which rendermodes the field is shown
                - Hidden # Hides the field in all render modes
                - View
                - Edit
                - Create
