name: 'Continuous Integration'
on: [ push, workflow_dispatch ]
env:
  GRADLE_OPTS: >-
    -Dorg.gradle.project.buildDate=$(date +%s)
    -Dorg.gradle.project.org.alfresco.maven.nexus.username=${{ secrets.ALFRESCO_NEXUS_USERNAME }}
    -Dorg.gradle.project.org.alfresco.maven.nexus.password=${{ secrets.ALFRESCO_NEXUS_PASSWORD }}
    -Dorg.gradle.project.eu.xenit.cloudsmith.username=${{ secrets.CLOUDSMITH_USER }} 
    -Dorg.gradle.project.eu.xenit.cloudsmith.password=${{ secrets.CLOUDSMITH_APIKEY }}
jobs:
  continuousIntegration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_JENKINS_KEY }}
            ${{ secrets.DEPLOY_KEY_ALFRED_API }}
            ${{ secrets.DEPLOY_KEY_ALFRED_API_DOCS }}
            ${{ secrets.DEPLOY_KEY_EDGE_DOCS }}
            ${{ secrets.DEPLOY_KEY_FINDER_DOCS }}
            ${{ secrets.DEPLOY_KEY_INFLOW_DOCS }}
      - name: init submodules
        run: |
          git submodule update --init --remote
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          registry: hub.xenit.eu
          username: ${{ secrets.XENIT_DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.XENIT_DOCKER_REGISTRY_PASSWORD }}
      - name: Build websites
        run: |
          [ -e "pandoc.deb" ] || curl -L https://github.com/jgm/pandoc/releases/download/1.17.2/pandoc-1.17.2-1-amd64.deb -o pandoc.deb
          echo "84fe35ed9be0f1d8eb6d4cc03d63a8e532e9776f pandoc.deb" | sha1sum -c
          dpkg -x pandoc.deb pandoc
          PATH="$(pwd)/pandoc/usr/bin":"$PATH" bash -x ./build-websites.sh
#      - name: 'Upload Artifact'
#        if: success()
#        uses: actions/upload-artifact@v3
#        with:
#          name: website
#          path: /home/runner/work/alfred-docs/alfred-docs/**/build/website.tar.gz
#          retention-days: 2
      - name: Information docx
        run: |
          pwd
          ls -l
          ls -l build/
          ls -l build/docx/
          ls -l build/docx/alfred-desktop/
          ls -l build/docx/alfred-desktop/4.2/
      - name: Information normalized
        run: |
          pwd
          ls -l
          ls -l build/
          ls -l build/normalized/
          ls -l build/normalized/alfred-desktop/
      - name: Information normalized
        run: |
          pwd
          ls -l
          ls -l build/
          ls -l build/product/
          ls -l build/product/alfred-desktop/
#      - name: Archive Alfred Desktop artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: alfred-desktop
#          path: /home/runner/work/alfred-docs/alfred-docs/build/normalized/alfred-desktop/4.2-out.tar
#          retention-days: 1